#!/bin/bash
backup ~/.vimrc
source_config vim/vimrc .vimrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install ag
if ! [ -x "$(command -v ag)" ]; then
  install silversearcher-ag
fi

# Install plugins
vim +PlugInstall +qall

cd $DOTFILES

