#!/bin/bash
backup ~/.zshrc
source_config_wpath zsh/zshrc .zshrc

echo "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh" >> ~/.zshrc

clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.zsh-autosuggestions
clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh-syntax-highlighting

if [ ! -d $DOTFILES/local/zsh ]
then 
  mkdir $DOTFILES/local/zsh
  echo '# Put your "this computer only" keybindings here' > $DOTFILES/local/zsh/bindings.sh
fi

if [ -d ~/.fzf ]
then 
  echo "Fzf is already installed"
else
  clone "--depth 1 https://github.com/junegunn/fzf.git" ~/.fzf
  ~/.fzf/install
fi
