#!/bin/bash
backup ~/.zshrc
source_config_wpath zsh/zshrc .zshrc

echo "[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh" >> ~/.zshrc

OMZ=$DOTFILES/local/git/oh-my-zsh
ZAS=$DOTFILES/local/git/zsh-autosuggestions
ZAH=$DOTFILES/local/git/zsh-syntax-highlighting

echo "OMZ=$OMZ" >> $DOTFILES/.var
echo "ZAS=$ZAS" >> $DOTFILES/.var
echo "ZAH=$ZAH" >> $DOTFILES/.var

clone https://github.com/robbyrussell/oh-my-zsh.git $OMZ
clone https://github.com/zsh-users/zsh-autosuggestions.git $ZAS
clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZAH

if [ ! -d $DOTFILES/local/zsh ]
then 
  mkdir $DOTFILES/local/zsh
  echo '# Put your "this computer only" keybindings here' > $DOTFILES/local/zsh/bindings.sh
fi

if [ -d ~/.fzf ]
then 
  echo "Fzf is already installed"
else
  clone "--depth 1 https://github.com/junegunn/fzf.git" ~/.fzf
  ~/.fzf/install
fi
