if command -v tmux>/dev/null; then
    [ -z $TMUX ] && exec tmux
  else
    echo "tmux not installed, run make tmux in $DOTFILES to install"
fi

# Settings
HISTFILE=~/.zsh_history
SAVEHIST=3000
setopt inc_append_history # To save every command before it is executed
setopt hist_ignore_all_dups
setopt share_history # setopt inc_append_history

export VISUAL=vim

stty -ixon

# Plugins
source_plugin() {
  [[ -d $ZSH_PLUGINS/$1 ]] && source $ZSH_PLUGINS/$1/$1.plugin.zsh
}

source_plugin zsh-autosuggestions
source_plugin zsh-syntax-highlighting
source_plugin zsh-completions
source_plugin zsh-history-substring-search

export fpath=($ZSH_PLUGINS/zsh-completions/src $fpath)

source $DOTFILES/zsh/scripts/prompt.sh
source $DOTFILES/zsh/scripts/bindings.sh
source $DOTFILES/zsh/scripts/kubectl.zsh

# Completion
if [[ -f $HOME/.zcompdump ]]; then
  last_comp_dump=$(date -r $HOME/.zcompdump +%s)
  current_time=$( date +%s )
  autoload -Uz compinit
  if (( last_comp_dump < (current_time-(60*60*24)) )); then
    autoload -Uz compdump
    compinit
    compdump
  else
    compinit -C
  fi
else
  autoload -Uz compinit
  compinit
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
