if command -v tmux>/dev/null; then
    [ -z $TMUX ] && exec tmux
  else 
    echo "tmux not installed, run make tmux in $DOTFILES to install"
fi
# Vars
HISTFILE=~/.zsh_history
SAVEHIST=3000
setopt inc_append_history # To save every command before it is executed 
setopt hist_ignore_all_dups
setopt share_history # setopt inc_append_history

# Settings
export VISUAL=vim

stty -ixon

plugins=(
  git
  docker
  dnf
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

source $DOTFILES/zsh/scripts/prompt.sh
source $DOTFILES/zsh/scripts/fixls.zsh
source $DOTFILES/zsh/scripts/bindings.sh
source $DOTFILES/zsh/scripts/kubectl.zsh
